export const SMS_START = 'SMS_START'
export const SMS_SUCCESS = 'SMS_SUCCESS'
export const SMS_FAIL = 'SMS_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const NAME_START = 'NAME_START'
export const NAME_SUCCESS = 'NAME_SUCCESS'
export const NAME_FAIL = 'NAME_FAIL'

export const SHOW_SMS = 'SHOW_SMS'
export const HIDE_SMS = 'HIDE_SMS'

export const SHOW_AUTH = 'SHOW_AUTH'
export const HIDE_AUTH = 'HIDE_AUTH'

export const SHOW_NAME = 'SHOW_NAME'
export const HIDE_NAME = 'HIDE_NAME'

export const FETCH_TOP_CAT_START = 'FETCH_TOP_CAT_START'
export const FETCH_TOP_CAT_SUCCESS = 'FETCH_TOP_CAT_SUCCESS'
export const FETCH_TOP_CAT_FAIL = 'FETCH_TOP_CAT_FAIL'

export const FETCH_POP_BRANDS_START = 'FETCH_POP_BRANDS_START'
export const FETCH_POP_BRANDS_SUCCESS = 'FETCH_POP_BRANDS_SUCCESS'
export const FETCH_POP_BRANDS_FAIL = 'FETCH_POP_BRANDS_FAIL'

export const FETCH_FEATURE_PRO_START = 'FETCH_FEATURE_PRO_START'
export const FETCH_FEATURE_PRO_SUCCESS = 'FETCH_FEATURE_PRO_SUCCESS'
export const FETCH_FEATURE_PRO_FAIL = 'FETCH_FEATURE_PRO_FAIL'

export const ADD_TO_CART_START = 'ADD_TO_CART_START'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL'

export const GET_CART_START = 'GET_CART_START'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAIL = 'GET_CART_FAIL'

export const UPDATE_CART_START = 'UPDATE_CART_START'
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS'
export const UPDATE_CART_FAIL = 'UPDATE_CART_FAIL'

export const DELETE_CART_START =    'DELETE_CART_START'
export const DELETE_CART_SUCCESS =  'DELETE_CART_SUCCESS'
export const DELETE_CART_FAIL =     'DELETE_CART_FAIL'


export const APPLY_PROMO_CODE_START =    'APPLY_PROMO_CODE_START'
export const APPLY_PROMO_CODE_SUCCESS =  'APPLY_PROMO_CODE_SUCCESS'
export const APPLY_PROMO_CODE_FAIL =     'APPLY_PROMO_CODE_FAIL'

export const GET_PROFILE_START = 'GET_PROFILE_START'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const GET_PRO_DETAILS_START =    'GET_PRO_DETAILS_START'
export const GET_PRO_DETAILS_SUCCESS =  'GET_PRO_DETAILS_SUCCESS'
export const GET_PRO_DETAILS_FAIL =     'GET_PRO_DETAILS_FAIL'

export const GET_MY_ORDERS_START =    'GET_MY_ORDERS_START'
export const GET_MY_ORDERS_SUCCESS =  'GET_MY_ORDERS_SUCCESS'
export const GET_MY_ORDERS_FAIL =     'GET_MY_ORDERS_FAIL'

export const EDIT_ADDRESS_START =    'EDIT_ADDRESS_START'
export const EDIT_ADDRESS_SUCCESS =  'EDIT_ADDRESS_SUCCESS'
export const EDIT_ADDRESS_FAIL =     'EDIT_ADDRESS_FAIL'

export const DELETE_ADDRESS_START =    'DELETE_ADDRESS_START'
export const DELETE_ADDRESS_SUCCESS =  'DELETE_ADDRESS_SUCCESS'
export const DELETE_ADDRESS_FAIL =     'DELETE_ADDRESS_FAIL'

export const CREATE_ADDRESS_START =    'CREATE_ADDRESS_START'
export const CREATE_ADDRESS_SUCCESS =  'CREATE_ADDRESS_SUCCESS'
export const CREATE_ADDRESS_FAIL =     'CREATE_ADDRESS_FAIL'

export const CREATE_ORDER_START =    'CREATE_ORDER_START'
export const CREATE_ORDER_SUCCESS =  'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL =     'CREATE_ORDER_FAIL'

export const MERGE_CART_START =    'MERGE_CART_START'
export const MERGE_CART_SUCCESS =  'MERGE_CART_SUCCESS'
export const MERGE_CART_FAIL =     'MERGE_CART_FAIL'

export const PRODUCT_SEARCH_START =    'PRODUCT_SEARCH_START'
export const PRODUCT_SEARCH_SUCCESS =  'PRODUCT_SEARCH_SUCCESS'
export const PRODUCT_SEARCH_FAIL =     'PRODUCT_SEARCH_FAIL'

export const PRODUCT_CATEGORY_START =    'PRODUCT_CATEGORY_START'
export const PRODUCT_CATEGORY_SUCCESS =  'PRODUCT_CATEGORY_SUCCESS'
export const PRODUCT_CATEGORY_FAIL =     'PRODUCT_CATEGORY_FAIL'

export const GET_CATEGORIES_START =    'GET_CATEGORIES_START'
export const GET_CATEGORIES_SUCCESS =  'GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL =     'GET_CATEGORIES_FAIL'

export const GET_HEROSLIDER_START =    'GET_HEROSLIDER_START'
export const GET_HEROSLIDER_SUCCESS =  'GET_HEROSLIDER_SUCCESS'
export const GET_HEROSLIDER_FAIL =     'GET_HEROSLIDER_FAIL'

export const CREATE_REVIEW_START =    'CREATE_REVIEW_START'
export const CREATE_REVIEW_SUCCESS =  'CREATE_REVIEW_SUCCESS'
export const CREATE_REVIEW_FAIL =     'CREATE_REVIEW_FAIL'